apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
        - name: processing
          image: processing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5035   # âœ… corrected port
