apiVersion: apps/v1
kind: Deployment
metadata:
  name: processing-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processing
  template:
    metadata:
      labels:
        app: processing
    spec:
      containers:
        - name: processing
          image: processing-service:latest
          ports:
            - containerPort: 5035
---
apiVersion: v1
kind: Service
metadata:
  name: processing-service
spec:
  selector:
    app: processing
  ports:
    - protocol: TCP
      port: 5035
      targetPort: 5035
  type: ClusterIP
