apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: validation-service:latest
          ports:
            - containerPort: 5040
---
apiVersion: v1
kind: Service
metadata:
  name: validation-service
spec:
  selector:
    app: validation
  ports:
    - protocol: TCP
      port: 5040
      targetPort: 5040
      nodePort: 30004
  type: NodePort
